#!/bin/bash
echo "ALX" 
^C

root@571454a62166:/alx-pre_course/0x01-git/bash# cat > school
#!/bin/bash
echo "School"
^C
root@571454a62166:/alx-pre_course/0x01-git/bash# git add .
root@571454a62166:/alx-pre_course/0x01-git/bash# clear
